### Obtener lista de tipos de usuario
GET http://localhost:8080/v1/adminTypes
Content-Type: application/json


### Obtener lista de usuarios
GET http://localhost:8081/v1/user
Content-Type: application/json


### Obtener datos de usuario según su ID
GET http://localhost:8080/v1/user/1
Content-Type: application/json


### Obtener lista de usuario según el tipo de usuario y su estado
GET http://localhost:8080/v1/user/type=2/status=1
Content-Type: application/json


### Actualizar datos de administrador
PUT http://localhost:8081/v1/user/1
Content-Type: application/json

{
  "name" : "Prueba11111",
  "email" : "Prueba",
  "nickname" : "prueba1",
  "password" : "123",
  "typeUserId" : "1",
  "createDate" : "2022-02-22",
  "updateDate" : "2022-04-08",
  "status": "1"
}  


### Baja logica de negocio
DELETE http://localhost:8080/v1/adminBusiness
Content-Type: application/json

### Obtener lista de dueños de un negocio con estado activo
GET http://localhost:8081/v1/user/type=2/status=1
Content-Type: application/json

### Baja logica de dueño de negocio
PUT http://localhost:8081/v1/user/deleteOwner/6
Content-Type: application/json

{ 
  "status": "0" 
}  

