# --------------------------------- CITY
##### LEER TODAS LAS CIUDADES: esta ruta devuelve todas las ciudades en forma de lista.
GET http://localhost:8080/api/city
Content-Type: application/json


##### LEER UNA CIUDAD POR ID: esta ruta devuelve la ciudad asociada al id.
GET http://localhost:8080/api/city/1
Content-Type: application/json


##### CREAR UNA CIUDAD: esta ruta crea una ciudad con datos en formato "json".
POST http://localhost:8080/api/city
Content-Type: application/json

{
    "name": "La Paz"
}


##### ACTUALIZAR UNA CIUDAD POR ID: esta ruta actualza una sucursal con datos en formato "json" asociada al id.
PUT http://localhost:8080/api/city/1
Content-Type: application/json

{
    "name": "La Paz update"
}


##### BORRAR UNA CIUDAD POR ID: esta ruta borrar una ciudad asociada al id.
DELETE http://localhost:8080/api/city/1
Content-Type: application/json
