# --------------------------------- CUSTOM
##### READ COUNT BUSINESSES ----- GROUP 2 -----
GET http://localhost:8080/api/custom/countBusiness
Content-Type: application/json


##### READ BUSINESS ZONE BY ZONE ID ----- GROUP 2 -----
GET http://localhost:8080/api/custom/bussinesZone/1
Content-Type: application/json


##### READ BRANCH RATING COUNT ----- GROUP 5 -----
GET http://localhost:8080/api/custom/branchRatingCount
Content-Type: application/json


##### READ LOG GLOBAL COUNT ----- GROUP 5 -----
GET http://localhost:8080/api/custom/logGlobalCount
Content-Type: application/json


##### READ LOG ANUAL COUNT ----- GROUP 5 -----
GET http://localhost:8080/api/custom/logAnualCount
Content-Type: application/json


##### READ LOG SEMESTER COUNT ----- GROUP 5 -----
GET http://localhost:8080/api/custom/logSemesterCount
Content-Type: application/json


##### READ LOG QUARTER COUNT ----- GROUP 5 -----
GET http://localhost:8080/api/custom/logQuarterCount
Content-Type: application/json


##### READ LOG MONTH COUNT ----- GROUP 5 -----
GET http://localhost:8080/api/custom/logMonthCount
Content-Type: application/json


##### READ LOG DAY COUNT ----- GROUP 5 -----
GET http://localhost:8080/api/custom/logDayCount
Content-Type: application/json


##### READ LOG ANUAL COUNT BY USER ID ----- GROUP 2 -----
GET http://localhost:8080/api/custom/logAnualCount/userId/1
Content-Type: application/json


##### READ BUSINESS COUNT ACTIVE BRANCH ----- GROUP 2 -----
GET http://localhost:8080/api/custom/businessBranchActiveCount
Content-Type: application/json


##### READ BUSINESS RATING COUNT BY BUSINESS ID ----- GROUP 1 -----
GET http://localhost:8080/api/custom/businessRatingCount/businessId/1
Content-Type: application/json
