##### READ ALL CITIES
GET http://localhost:8080/api/city
Content-Type: application/json


##### READ A CITY BY ID
GET http://localhost:8080/api/city/4
Content-Type: application/json


##### CREATE A CITY
POST http://localhost:8080/api/city
Content-Type: application/json

{
    "name": 1
}


##### UPDATE A CITY BY ID
PUT http://localhost:8080/api/city/4
Content-Type: application/json

{
    "name": 1
}


##### DELETE A CITY BY ID
DELETE http://localhost:8080/api/city/1
Content-Type: application/json





##### READ ALL BUSINESSES
GET http://localhost:8080/api/business
Content-Type: application/json


##### READ A BUSINESS BY ID
GET http://localhost:8080/api/business/4
Content-Type: application/json


##### READ A BUSINESS BY USER ID
GET http://localhost:8080/api/business/?userId=4
Content-Type: application/json


##### CREATE A BUSINESS
POST http://localhost:8080/api/business
Content-Type: application/json

{
  "name": "business name",
  "description": "business description",
  "idTypeBusiness": 4,
  "createDate": "2008-01-02",
  "updateDate": "2008-01-02",
  "status": 0,
  "userIdUser": 4
}


##### UPDATE A BUSINESS BY ID
PUT http://localhost:8080/api/business/4
Content-Type: application/json

{
  "name": "business name",
  "description": "business description",
  "idTypeBusiness": 4,
  "createDate": "2008-01-02",
  "updateDate": "2008-01-02",
  "status": 1,
  "userIdUser": 4
}


##### DELETE A BUSINESS BY ID
DELETE http://localhost:8080/api/business/1
Content-Type: application/json





##### READ ALL BRANCHES
GET http://localhost:8080/api/branch
Content-Type: application/json


##### READ A BRANCH BY ID
GET http://localhost:8080/api/branch/4
Content-Type: application/json


##### READ A BRANCH BY ID
GET http://localhost:8080/api/branch/?businessId=4
Content-Type: application/json


##### CREATE A BRANCH
POST http://localhost:8080/api/branch
Content-Type: application/json

{
    "direction": "branch direction",
    "openHour": "2022-01-01T10:01:01",
    "closeHour": "2022-01-01T10:01:01",
    "attentionDays": "Monday",
    "image": "aW1hZ2UgZmlsZQ==",
    "idZone": 4,
    "idLocation": 4,
    "idBusiness": 104,
    "createDate": "2022-01-01",
    "updateDate": "2022-01-01",
    "status": 1
}


##### UPDATE A BRANCH BY ID
PUT http://localhost:8080/api/branch/4
Content-Type: application/json

{
    "direction": "branch direction",
    "openHour": "2022-01-01T10:01:01",
    "closeHour": "2022-01-01T10:01:01",
    "attentionDays": "Monday",
    "image": "aW1hZ2UgZmlsZQ==",
    "idZone": 4,
    "idLocation": 4,
    "idBusiness": 104,
    "createDate": "2022-01-01",
    "updateDate": "2022-01-01",
    "status": 1
}


##### DELETE A BRANCH BY ID
DELETE http://localhost:8080/api/branch/1
Content-Type: application/json









##### READ ALL LOCATIONS
GET http://localhost:8080/api/location
Content-Type: application/json


##### READ A LOCATION BY ID
GET http://localhost:8080/api/location/4
Content-Type: application/json


##### CREATE A LOCATION
POST http://localhost:8080/api/location
Content-Type: application/json

{
    "latitude": 0.0,
    "longitude": 0.0
}


##### UPDATE A LOCATION BY ID
PUT http://localhost:8080/api/location/4
Content-Type: application/json

{
    "latitude": 0.0,
    "longitude": 0.0
}


##### DELETE A LOCATION BY ID
DELETE http://localhost:8080/api/location/1
Content-Type: application/json
