##### READ ALL CITIES
GET http://localhost:8080/api/city
Content-Type: application/json


##### READ A CITY BY ID
GET http://localhost:8080/api/city/4
Content-Type: application/json


##### CREATE A CITY
POST http://localhost:8080/api/city
Content-Type: application/json

{
    "name": 1
}


##### UPDATE A CITY BY ID
PUT http://localhost:8080/api/city/4
Content-Type: application/json

{
    "name": 1
}


##### DELETE A CITY BY ID
DELETE http://localhost:8080/api/city/1
Content-Type: application/json





##### READ ALL BUSINESSES
GET http://localhost:8080/api/business
Content-Type: application/json


##### READ A BUSINESS BY ID
GET http://localhost:8080/api/business/4
Content-Type: application/json


##### CREATE A BUSINESS
POST http://localhost:8080/api/business
Content-Type: application/json

{
  "name": "business name",
  "description": "business description",
  "idTypeBusiness": 4,
  "createDate": "2008-01-02",
  "updateDate": "2008-01-02",
  "status": 0,
  "userIdUser": 4
}


##### UPDATE A BUSINESS BY ID
PUT http://localhost:8080/api/business/4
Content-Type: application/json

{
  "name": "business name",
  "description": "business description",
  "idTypeBusiness": 4,
  "createDate": "2008-01-02",
  "updateDate": "2008-01-02",
  "status": 1,
  "userIdUser": 4
}


##### DELETE A BUSINESS BY ID
DELETE http://localhost:8080/api/business/1
Content-Type: application/json
