###
POST http://localhost:80/recover
Content-Type: application/json

{
  "email": "sv.kokonoe@gmail.com"
}

###
GET http://localhost:80/reset-password?user=test_si

###
POST http://localhost:80/reset-password
Content-Type: application/json

{
  "nickname": "test_si",
  "password": "test"
}