# --------------------------------- USER CRUD


##### LEER TODOS LOS USUARIO: esta ruta devuelve todos los usuarios en forma de lista.
GET http://localhost:8080/v1/api/user


# --------------------------------- USER BY GROUP


##### BORRAR UN USUARIO POR ID ACTUALIZANDO LOS NEGOCIOS Y SUCURSALES: ----- GROUP 2 ----- esta ruta borra un usuario asociado al id. Actualzia el estado logico de los negocios y sucursales asociado a 0 o 1.
DELETE http://localhost:8080/v1/api/user/1


##### LEER USUARIOS POR TIPO Y ESTATUS: ----- GROUP 2 ----- esta ruta devuelve los usuarios por tipo y estatus.
GET http://localhost:8080/v1/api/user/type=3/status=1
Content-Type: application/json
