##### DELETE A USER BY ID CASCATING DELETE TO BUSINESS AND BRANCH ----- GROUP 2 -----
DELETE http://localhost:8080/v1/api/user/1


### READ ALL USERS
GET http://localhost:8080/v1/api/user


### Obtener lista de dueños de un negocio con estado activo
GET http://localhost:8080/v1/api/user/type=1/status=1
Content-Type: application/json