version: '3.8'

services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    command: --init-file /db/service_maps_create.sql
    volumes:
      - ./db/service_maps_create.sql:/db/service_maps_create.sql
    ports:
      - 3306:3306

volumes:
  db:
    driver: local